// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbxlpnqhnsiarhdgrmty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieGxwbnFobnNpYXJoZGdybXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTg0MDAsImV4cCI6MjA1NzQ5NDQwMH0.bQjsedOUG5q8B2QwIEF7mhtrurf4A2wcCS8sJam5gjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);